# POSTGRESQL DATABASE PARAMETERS:
# Database name (development)
# Database name (testing)
# Database name (production)
# Username 
# Password
# NOTE: All three databases use the same username and password.

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['var_db_omni_20171006_200007_650_username'] %>
  password: <%= ENV['var_db_omni_20171006_200007_650_password'] %>

development:
  <<: *default
  database: db_omni_20171006_200007_650_dev

test:
  <<: *default
  database: db_omni_20171006_200007_650_test

production:
  <<: *default
  database: db_omni_20171006_200007_650_pro
